/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AirplaneScript")]
    [LuaRegisterType(0x297f88064394b7b8, typeof(LuaBehaviour))]
    public class AirplaneScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c573c87ea1181d14aa506d9cbbfeafb9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Airplane = default;
        [SerializeField] public UnityEngine.GameObject m_CameraObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Airplane),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_CameraObject),
            };
        }
    }
}

#endif
