/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AnimatedAnchorScript")]
    [LuaRegisterType(0x1e146bb7f3d16f42, typeof(LuaBehaviour))]
    public class AnimatedAnchorScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "cca99f4f85ef4f44f9fcb4ba543a39fc";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_myAnchorGO = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_myAnchorGO),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/AnimatedAnchorScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
