/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ConstSPin")]
    [LuaRegisterType(0xb9df465aa985dab4, typeof(LuaBehaviour))]
    public class ConstSPin : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "66a523c7efd151b4b8b97add76c5b84b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_rotationSpeed = 25;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_rotationSpeed),
            };
        }
    }
}

#endif
