/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaRegisterType(0x64f367123469100e, typeof(LuaBehaviour))]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "569067bf74c210d4f8075272b08f2ed3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_rockEffect = default;
        [SerializeField] public UnityEngine.GameObject m_bloodParticle = default;
        [SerializeField] public UnityEngine.GameObject m_paperEffect = default;
        [SerializeField] public UnityEngine.GameObject m_scissorsEffect = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_rockEffect),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_bloodParticle),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_paperEffect),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_scissorsEffect),
            };
        }
    }
}

#endif
