/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerCharacterControllerAFKPrevention")]
    [LuaRegisterType(0xb816c3eb3e62e201, typeof(LuaBehaviour))]
    public class PlayerCharacterControllerAFKPrevention : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "03c9bb9e0b7ceed4ea13018038cf1a32";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_movementIndicator = default;
        [SerializeField] public Highrise.AudioShader m_longPressSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepWalkSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepRunSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_movementIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_longPressSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_footstepWalkSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_footstepRunSound),
            };
        }
    }
}

#endif
