/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "774dcf26d00efc74ab4ed9d9ab0cc25d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_mainHUDOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_resultsOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_leaderboardOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_hudButtonsOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_welcomObj = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_mainHUDOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_resultsOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_leaderboardOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_hudButtonsOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_welcomObj),
            };
        }
    }
}

#endif
