/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DanceGameManager")]
    [LuaRegisterType(0xb02ae22bda27395, typeof(LuaBehaviour))]
    public class DanceGameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8ae205b18d672cb46b6186f64fb11ba2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_prefabToSpawn = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_prefabToSpawn),
            };
        }
    }
}

#endif
