/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIModule")]
    [LuaRegisterType(0xe8e6e3a8703514f7, typeof(LuaBehaviour))]
    public class UIModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9c6832eb1f309f24f904ebf261cfa471";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_TimerObj = default;
        [SerializeField] public UnityEngine.GameObject m_MidScoreObj = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_TimerObj),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_MidScoreObj),
            };
        }
    }
}

#endif
