/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaRegisterType(0x64f367123469100e, typeof(LuaBehaviour))]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4a274a46d1bf27d41948f9a8d0005d6b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_camerScript = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_LinePlaces = default;
        [Header("Fart")]
        [SerializeField] public System.Double m_fartCost = 150;
        [SerializeField] public UnityEngine.GameObject m_fartParticle = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.AudioShader> m_fartSounds = default;
        [Header("FartBomb")]
        [SerializeField] public System.Double m_fartBombCost = 1000;
        [SerializeField] public UnityEngine.GameObject m_fartBombParticle = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.AudioShader> m_fartBombSounds = default;
        [Header("ToiletParty")]
        [SerializeField] public System.Double m_toiletPartyCost = 1000;
        [SerializeField] public UnityEngine.GameObject m_toiletPartyParticle = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.AudioShader> m_toiletPartySounds = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_camerScript),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_LinePlaces),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_fartCost),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_fartParticle),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_fartSounds),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_fartBombCost),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_fartBombParticle),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_fartBombSounds),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_toiletPartyCost),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_toiletPartyParticle),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_toiletPartySounds),
            };
        }
    }
}

#endif
