/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HudButtons")]
    [LuaRegisterType(0x2d969c13a34cc4ef, typeof(LuaBehaviour))]
    public class HudButtons : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1055ebde19d1db64fa9f4d63b8ee4447";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_buttonIcons = default;
        [LuaScriptPropertyAttribute("475196c2905476841b34b4cc6e015986")]
        [SerializeField] public UnityEngine.Object m_fartCloudData = default;
        [LuaScriptPropertyAttribute("475196c2905476841b34b4cc6e015986")]
        [SerializeField] public UnityEngine.Object m_fartBombData = default;
        [LuaScriptPropertyAttribute("475196c2905476841b34b4cc6e015986")]
        [SerializeField] public UnityEngine.Object m_fireAlarmData = default;
        [LuaScriptPropertyAttribute("475196c2905476841b34b4cc6e015986")]
        [SerializeField] public UnityEngine.Object m_toiletPartyData = default;
        [LuaScriptPropertyAttribute("475196c2905476841b34b4cc6e015986")]
        [SerializeField] public UnityEngine.Object m_poopHeadData = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_buttonIcons),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fartCloudData),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_fartBombData),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_fireAlarmData),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_toiletPartyData),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_poopHeadData),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HudButtons/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
