/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/LineSimPlayerController")]
    [LuaRegisterType(0xb462a9b8cd7f2293, typeof(LuaBehaviour))]
    public class LineSimPlayerController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3617c21bb01f8994db5d5cba1baccd34";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_movementIndicator = default;
        [SerializeField] public Highrise.AudioShader m_longPressSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepWalkSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepRunSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_movementIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_longPressSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_footstepWalkSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_footstepRunSound),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/LineSimPlayerController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
