/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MusicManager")]
    [LuaRegisterType(0x429426726861b96b, typeof(LuaBehaviour))]
    public class MusicManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4101887a59532a04fbbe2b64f71ffebe";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_outsideMusic = default;
        [SerializeField] public Highrise.AudioShader m_insideMusic = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_outsideMusic),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_insideMusic),
            };
        }
    }
}

#endif
