/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PosterLink")]
    [LuaRegisterType(0xbe157d35701194ec, typeof(LuaBehaviour))]
    public class PosterLink : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d4988489c03951943852fa92f23edd0a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_userID = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_userID),
            };
        }
    }
}

#endif
