/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f084c50d0853d894c987eaa9e8915995";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_ActionButtonOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_HudButtonsOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_PurchaseConfirmationOBJ = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ActionButtonOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_HudButtonsOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_PurchaseConfirmationOBJ),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
