/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/arenaUIManager")]
    [LuaRegisterType(0xbcdf50793b7561b1, typeof(LuaBehaviour))]
    public class arenaUIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4666489c8e16da0489d350c0852939dc";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_lobbyhudOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_timerHudOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_actionsHandOBJ = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lobbyhudOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_timerHudOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_actionsHandOBJ),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/arenaUIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
