/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaRegisterType(0x64f367123469100e, typeof(LuaBehaviour))]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "525e4cf3fc9e8ef4ca6713806cc6d58b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_playerPlaces = default;
        [SerializeField] public UnityEngine.Transform m_bossAttackPlace = default;
        [SerializeField] public System.Double m_joinTime = 30;
        [SerializeField] public System.Double m_turnTime = 15;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_playerPlaces),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_bossAttackPlace),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_joinTime),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_turnTime),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/GameManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
