/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ChatBoothUI")]
    [LuaRegisterType(0x91662a13aedac973, typeof(LuaBehaviour))]
    public class ChatBoothUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "35bb0e6cbb1ad8b40b8273cba4ddb534";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("9cd95e5343f5ecd4cb4dc80396d37cea")]
        [SerializeField] public UnityEngine.Object m_boothController = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_boothController),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ChatBoothUI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
