/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ClothesCanvasModule")]
    [LuaRegisterType(0x42fa104895ca1113, typeof(LuaBehaviour))]
    public class ClothesCanvasModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "746bfa361eaaaab4ab419094a6e3f422";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("a8f17c7392ff9154f9946caf73d2b655")]
        [SerializeField] public UnityEngine.Object m_pixelArtCanvas = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_pixelArtCanvas),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ClothesCanvasModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
