/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollabEmoteController")]
    [LuaRegisterType(0xbc0732ca26370630, typeof(LuaBehaviour))]
    public class CollabEmoteController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fafd9377be1ff3f4894509499fc5f6c3";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("If true, uses NavMeshAgent for movement detection. If false, uses position-based detection.")]
        [SerializeField] public System.Boolean _useNavMeshAgent = true;
        [Tooltip("NavMesh area mask to use when sampling positions. Default is all areas (-1).")]
        [SerializeField] public System.Double _navMeshAreaMask = -1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _useNavMeshAgent),
                CreateSerializedProperty(_script.GetPropertyAt(1), _navMeshAreaMask),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CollabEmoteController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
