/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DialoguePage")]
    [LuaRegisterType(0x3a23ac4294318728, typeof(LuaScriptableObject))]
    public class DialoguePage : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "5f7dbb76983dd93469a12bb278d8bb78";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_messagesData = "";
        [SerializeField] public System.Collections.Generic.List<System.String> m_responses = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_responseIDs = default;
        [LuaScriptPropertyAttribute("3d0bd200f8ab7b948aa8f0034f550645")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_Chunks = default;
        [SerializeField] public System.String m_NPCEmote = "";
        [SerializeField] public UnityEngine.Texture m_PageImage = default;
        [SerializeField] public Highrise.AudioShader m_Sound = default;
        [SerializeField] public Highrise.CharacterOutfit m_npcOutfit = default;
        [SerializeField] public System.Boolean m_showNPC = true;
        [SerializeField] public System.String m_nameOverride = "";
        [SerializeField] public UnityEngine.Texture m_bgOverride = default;
        [SerializeField] public UnityEngine.Texture2D m_npcImageOverride = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_messagesData),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_responses),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_responseIDs),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Chunks),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_NPCEmote),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_PageImage),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_Sound),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_npcOutfit),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_showNPC),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_nameOverride),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_bgOverride),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_npcImageOverride),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DialoguePage/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
