/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DropFourManager")]
    [LuaRegisterType(0x35d6b33052eaef8f, typeof(LuaBehaviour))]
    public class DropFourManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "905b3c911f8e6a04089781861149e98b";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("How many Drop Four tables this world has. Place one DropFourTable prefab per table, with tableId 1..N.")]
        [SerializeField] public System.Double m_tableCount = 2;
        [Tooltip("TESTING ONLY. Lets the host start with nobody else seated, alternating disc colors each drop so one player can play both sides. Turn this OFF before publishing.")]
        [SerializeField] public System.Boolean m_allowSoloTesting = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tableCount),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_allowSoloTesting),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DropFourManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
