/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DropFourLauncherUI")]
    [LuaRegisterType(0x347b942ecd25ba12, typeof(LuaBehaviour))]
    public class DropFourLauncherUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "25b877cf908d073479caca337b846e92";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The DropFourManager on the parent GameObject. It is a ClientAndServer script, not a Module, so it must be referenced here rather than required.")]
        [LuaScriptPropertyAttribute("905b3c911f8e6a04089781861149e98b")]
        [SerializeField] public UnityEngine.Object m_manager = default;
        [Tooltip("The GameObject carrying DropFourHUD.")]
        [SerializeField] public UnityEngine.GameObject m_hudObject = default;
        [Tooltip("The GameObject carrying DropFourBoardUI.")]
        [SerializeField] public UnityEngine.GameObject m_boardObject = default;
        [Tooltip("The GameObject carrying DropFourLobbyUI.")]
        [SerializeField] public UnityEngine.GameObject m_lobbyObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_manager),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_hudObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_boardObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_lobbyObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DropFourLauncherUI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
