/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DropFourTableTap")]
    [LuaRegisterType(0x91331be87ebe8779, typeof(LuaBehaviour))]
    public class DropFourTableTap : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "246f254f0d995664d9c3d34aa7e73c3d";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Which table this is. Must be between 1 and the manager's tableCount.")]
        [SerializeField] public System.Double m_tableId = 1;
        [Tooltip("The DropFourManager (same instance the lobby and launcher reference); supplies this table's seat count. It is a ClientAndServer script, not a Module, so it must be referenced here rather than required.")]
        [LuaScriptPropertyAttribute("905b3c911f8e6a04089781861149e98b")]
        [SerializeField] public UnityEngine.Object m_manager = default;
        [Tooltip("Optional indicator art for 1 seated player. Leave empty to keep the prefab's default texture.")]
        [SerializeField] public UnityEngine.Texture2D m_icon1Player = default;
        [Tooltip("Optional indicator art for 2 seated players.")]
        [SerializeField] public UnityEngine.Texture2D m_icon2Players = default;
        [Tooltip("Optional indicator art for 3 seated players.")]
        [SerializeField] public UnityEngine.Texture2D m_icon3Players = default;
        [Tooltip("Optional indicator art for 4 seated players.")]
        [SerializeField] public UnityEngine.Texture2D m_icon4Players = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tableId),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_manager),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_icon1Player),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_icon2Players),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_icon3Players),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_icon4Players),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DropFourTableTap/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
