/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DropFourHUD")]
    [LuaRegisterType(0x5514fc83a34b8379, typeof(LuaBehaviour))]
    public class DropFourHUD : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4c21aece359074d45bf61413e1586e88";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The DropFourManager on the parent GameObject. It is a ClientAndServer script, not a Module, so it must be referenced here rather than required.")]
        [LuaScriptPropertyAttribute("905b3c911f8e6a04089781861149e98b")]
        [SerializeField] public UnityEngine.Object m_manager = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_manager),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DropFourHUD/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
