/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MergeIslandHUD")]
    [LuaRegisterType(0x68bd27fb0410cf9b, typeof(LuaBehaviour))]
    public class MergeIslandHUD : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "be0a75302bf24ba44a4f8b1f659151fd";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Item art, ONE SPRITE PER TIER, ordered bottom of the ladder to top. Index 1 = tier 1. Any tier left empty falls back to its placeholder colour and tier number, so a partly-filled list is fine while you are still making art.")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Sprite> m_tierSprites = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tierSprites),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), null),
                CreateSerializedProperty(_script.GetPropertyAt(19), null),
                CreateSerializedProperty(_script.GetPropertyAt(20), null),
                CreateSerializedProperty(_script.GetPropertyAt(21), null),
                CreateSerializedProperty(_script.GetPropertyAt(22), null),
                CreateSerializedProperty(_script.GetPropertyAt(23), null),
                CreateSerializedProperty(_script.GetPropertyAt(24), null),
                CreateSerializedProperty(_script.GetPropertyAt(25), null),
                CreateSerializedProperty(_script.GetPropertyAt(26), null),
                CreateSerializedProperty(_script.GetPropertyAt(27), null),
                CreateSerializedProperty(_script.GetPropertyAt(28), null),
                CreateSerializedProperty(_script.GetPropertyAt(29), null),
                CreateSerializedProperty(_script.GetPropertyAt(30), null),
                CreateSerializedProperty(_script.GetPropertyAt(31), null),
                CreateSerializedProperty(_script.GetPropertyAt(32), null),
                CreateSerializedProperty(_script.GetPropertyAt(33), null),
                CreateSerializedProperty(_script.GetPropertyAt(34), null),
                CreateSerializedProperty(_script.GetPropertyAt(35), null),
                CreateSerializedProperty(_script.GetPropertyAt(36), null),
                CreateSerializedProperty(_script.GetPropertyAt(37), null),
                CreateSerializedProperty(_script.GetPropertyAt(38), null),
                CreateSerializedProperty(_script.GetPropertyAt(39), null),
                CreateSerializedProperty(_script.GetPropertyAt(40), null),
                CreateSerializedProperty(_script.GetPropertyAt(41), null),
                CreateSerializedProperty(_script.GetPropertyAt(42), null),
                CreateSerializedProperty(_script.GetPropertyAt(43), null),
                CreateSerializedProperty(_script.GetPropertyAt(44), null),
                CreateSerializedProperty(_script.GetPropertyAt(45), null),
                CreateSerializedProperty(_script.GetPropertyAt(46), null),
                CreateSerializedProperty(_script.GetPropertyAt(47), null),
                CreateSerializedProperty(_script.GetPropertyAt(48), null),
                CreateSerializedProperty(_script.GetPropertyAt(49), null),
                CreateSerializedProperty(_script.GetPropertyAt(50), null),
                CreateSerializedProperty(_script.GetPropertyAt(51), null),
                CreateSerializedProperty(_script.GetPropertyAt(52), null),
                CreateSerializedProperty(_script.GetPropertyAt(53), null),
                CreateSerializedProperty(_script.GetPropertyAt(54), null),
                CreateSerializedProperty(_script.GetPropertyAt(55), null),
                CreateSerializedProperty(_script.GetPropertyAt(56), null),
                CreateSerializedProperty(_script.GetPropertyAt(57), null),
                CreateSerializedProperty(_script.GetPropertyAt(58), null),
                CreateSerializedProperty(_script.GetPropertyAt(59), null),
                CreateSerializedProperty(_script.GetPropertyAt(60), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MergeIslandHUD/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
