/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MergeIslandKit")]
    [LuaRegisterType(0x5e30d0fafd8e55da, typeof(LuaBehaviour))]
    public class MergeIslandKit : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "cc27337e81d465c48adfbf01ec767329";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean _debugCheats = false;
        [SerializeField] public System.Boolean _debugWindowClosed = false;
        [SerializeField] public System.Double _debugCurrencyLatency = 0;
        [SerializeField] public System.Boolean _debugFailLoad = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _debugCheats),
                CreateSerializedProperty(_script.GetPropertyAt(1), _debugWindowClosed),
                CreateSerializedProperty(_script.GetPropertyAt(2), _debugCurrencyLatency),
                CreateSerializedProperty(_script.GetPropertyAt(3), _debugFailLoad),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MergeIslandKit/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
