/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RythmGameController")]
    [LuaRegisterType(0x5968fc430688111, typeof(LuaBehaviour))]
    public class RythmGameController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a09989c11d0fcad4b9ddb498acd62144";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_SongFile = default;
        [LuaScriptPropertyAttribute("a7228f6c1a153db48b3284834c165986")]
        [SerializeField] public UnityEngine.Object m_gameUI = default;
        [LuaScriptPropertyAttribute("0927e5fadc3b0bf41b6b2f1d59698d54")]
        [SerializeField] public UnityEngine.Object m_RewardParticlesUI = default;
        [LuaScriptPropertyAttribute("6ade8fd984ade854795af1e71100797d")]
        [SerializeField] public UnityEngine.Object m_Mainmenu = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SongFile),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_gameUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_RewardParticlesUI),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Mainmenu),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RythmGameController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
