/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RythmGameMenuUI")]
    [LuaRegisterType(0x20db8b215c3d22c, typeof(LuaBehaviour))]
    public class RythmGameMenuUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6ade8fd984ade854795af1e71100797d";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("ca00bfe6a1236a641b74bfca478fbf31")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_SongDataList = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SongDataList),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RythmGameMenuUI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
