/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ShirtSprite")]
    [LuaRegisterType(0x555a9c8f2b039c5a, typeof(LuaBehaviour))]
    public class ShirtSprite : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "cfe74a6d87d2d7540b328fd344d35142";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ShirtSprite/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
