/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/SongEntry")]
    [LuaRegisterType(0xa46410a2f9254098, typeof(LuaScriptableObject))]
    public class SongEntry : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "ca00bfe6a1236a641b74bfca478fbf31";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_SongShader = default;
        [SerializeField] public System.String m_SongName = "";
        [SerializeField] public System.Double m_SongBPM = 120;
        [SerializeField] public System.Double m_SongDuration = 120;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SongShader),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_SongName),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_SongBPM),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_SongDuration),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SongEntry/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
