/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DesignHudButton")]
    [LuaRegisterType(0xfea90ee4eb1efd98, typeof(LuaBehaviour))]
    public class DesignHudButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "537f887cbe196d34491af46d13fb19c9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_kiteBuilderObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_kiteBuilderObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DesignHudButton/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
