/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DualModeController")]
    [LuaRegisterType(0xfa52597ba685ccd0, typeof(LuaBehaviour))]
    public class DualModeController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "07bf5f387821e2344b6bc65268140d55";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_movementUpdateInterval = 0.1;
        [SerializeField] public Highrise.AudioShader m_footstepWalkSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepRunSound = default;
        [Tooltip("Keyboard and gamepad input used on Desktop clients")]
        [SerializeField] public UnityEngine.InputSystem.InputActionReference m_externalInputAction = default;
        [SerializeField] public System.Double _startingMovementSpeed = 5.5;
        [SerializeField] public System.Double _smoothTime = 0.15;
        [SerializeField] public System.Double _movementSpeed = 5.5;
        [Tooltip("The running emote will be used beyond this speed")]
        [SerializeField] public System.Double m_runningSpeedThreshold = 5;
        [SerializeField] public System.Double _turnAroundThreshold = -0.5;
        [Tooltip("If checked the input to world space transform will not ignore the Y coordinate")]
        [SerializeField] public System.Boolean m_is2D = false;
        [Header("These properties determine if you should use an off-mesh link")]
        [Tooltip("You have to be within this distance of an off-mesh link endpoint to use it")]
        [SerializeField] public System.Double m_maxLinkDistance = 1;
        [Tooltip("The euler angle between your movement vector and the link vector has to be within this value to use it")]
        [SerializeField] public System.Double m_maxLinkAngle = 95;
        [Tooltip("The difference between the requested step size and the actual step size. 0 means no change, 1 means the character couldn't move at all in that direction. If the difference is above this value and all the other criteria are met the off-mesh link will be used")]
        [SerializeField] public System.Double m_minLinkMoveStepChange = 0.24;
        [Header("Drag Movement Configuration")]
        [Tooltip("Camera used for screen to world position conversion")]
        [SerializeField] public UnityEngine.Camera m_movementCamera = default;
        [Tooltip("Maximum distance for movement target")]
        [SerializeField] public System.Double m_maxMovementDistance = 50;
        [Tooltip("How close the character needs to be to the target before stopping")]
        [SerializeField] public System.Double m_arrivalThreshold = 0.5;
        [SerializeField] public System.Double _tapToMoveThreshold = 0.05;
        [SerializeField] public System.Double _rotationScreenThreshold = 0.6;
        [Header("Tap to Move Configuration")]
        [Tooltip("Movement indicator prefab to show tap destination")]
        [SerializeField] public UnityEngine.GameObject m_movementIndicator = default;
        [Tooltip("Sound to play on long press")]
        [SerializeField] public Highrise.AudioShader m_longPressSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_movementUpdateInterval),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_footstepWalkSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_footstepRunSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_externalInputAction),
                CreateSerializedProperty(_script.GetPropertyAt(4), _startingMovementSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(5), _smoothTime),
                CreateSerializedProperty(_script.GetPropertyAt(6), _movementSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_runningSpeedThreshold),
                CreateSerializedProperty(_script.GetPropertyAt(8), _turnAroundThreshold),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_is2D),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_maxLinkDistance),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_maxLinkAngle),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_minLinkMoveStepChange),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_movementCamera),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_maxMovementDistance),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_arrivalThreshold),
                CreateSerializedProperty(_script.GetPropertyAt(16), _tapToMoveThreshold),
                CreateSerializedProperty(_script.GetPropertyAt(17), _rotationScreenThreshold),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_movementIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_longPressSound),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DualModeController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
