/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/KiteConstructor")]
    [LuaRegisterType(0xe66e79c63764fcd6, typeof(LuaBehaviour))]
    public class KiteConstructor : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f841364933804e64d97d4756432bb5f8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_canvas = default;
        [SerializeField] public System.Double m_partSize = 0.1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_canvas),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_partSize),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/KiteConstructor/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
