/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/KitePartsManager")]
    [LuaRegisterType(0xbcaddc199338de4b, typeof(LuaBehaviour))]
    public class KitePartsManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "99b1fbeaf4175564cb4c6ebe55c4af34";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("ab452b26068fb8e4fa8158274c2283c3")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_kiteParts = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_kiteParts),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/KitePartsManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
