/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/KitePart")]
    [LuaRegisterType(0xf2ecd3b657389e4f, typeof(LuaScriptableObject))]
    public class KitePart : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "ab452b26068fb8e4fa8158274c2283c3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Sprite m_sprite = default;
        [SerializeField] public System.String m_partId = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_sprite),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_partId),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/KitePart/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
