/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/KiteController")]
    [LuaRegisterType(0xa8c4f6c4a82a5dc6, typeof(LuaBehaviour))]
    public class KiteController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "40b5cbeb50e08184d902e152476bf8cb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_lineLength = 10;
        [SerializeField] public UnityEngine.Transform m_dropShadow = default;
        [SerializeField] public UnityEngine.Transform m_kiteRenderer = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lineLength),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_dropShadow),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_kiteRenderer),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/KiteController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
