/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DrawingCanvas")]
    [LuaRegisterType(0xed94efcdfaf3d5d1, typeof(LuaBehaviour))]
    public class DrawingCanvas : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4eabc49d61333794f9c3e0fab1585e24";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_canvasQuad = default;
        [SerializeField] public UnityEngine.GameObject m_cameraOBJ = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_canvasQuad),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_cameraOBJ),
            };
        }
    }
}

#endif
