/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaRegisterType(0x54ef1694c40a5ef8, typeof(LuaBehaviour))]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "07874ccf9edd95e42a0fa68b2089ba6b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_BGMusic = default;
        [SerializeField] public Highrise.AudioShader m_wavesSound = default;
        [SerializeField] public Highrise.AudioShader m_matchSound = default;
        [SerializeField] public Highrise.AudioShader m_passSound = default;
        [SerializeField] public Highrise.AudioShader m_shimmerLoop = default;
        [SerializeField] public Highrise.AudioShader m_rustleSound = default;
        [SerializeField] public Highrise.AudioShader m_popSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_BGMusic),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_wavesSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_matchSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_passSound),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_shimmerLoop),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_rustleSound),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_popSound),
            };
        }
    }
}

#endif
