/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BoatController")]
    [LuaRegisterType(0xad7f6b82965e6db7, typeof(LuaBehaviour))]
    public class BoatController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "781d3704b68af5e4f89b37e85c4c8578";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_moveSpeed = 1;
        [SerializeField] public System.Double m_radius = 5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_moveSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_radius),
            };
        }
    }
}

#endif
