/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameStateManager")]
    [LuaRegisterType(0x49dcb8913c32a6b7, typeof(LuaBehaviour))]
    public class GameStateManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8a82b7116bc901f409f547132389a3cc";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_boatPrefab = default;
        [SerializeField] public System.Double m_stateDuration = 60;
        [SerializeField] public UnityEngine.Camera m_mainCamera = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_boatPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_stateDuration),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_mainCamera),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/GameStateManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
