/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerCharacterControllerOverrides")]
    [LuaRegisterType(0x613211b8072917a8, typeof(LuaBehaviour))]
    public class PlayerCharacterControllerOverrides : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fd18c583b657273409ee77eb3ba0d8b3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_movementIndicator = default;
        [SerializeField] public Highrise.AudioShader m_longPressSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepWalkSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepRunSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_movementIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_longPressSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_footstepWalkSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_footstepRunSound),
            };
        }
    }
}

#endif
