/*

    Copyright (c) 2026 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "69d20f6fdf3c6974b8ceac3a7d73c1c6";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_TimerUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_SelectionUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_resultsUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_cinematicOverlayObj = default;
        [SerializeField] public UnityEngine.GameObject m_leaderboardUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_hudButtonsUIObj = default;
        [LuaScriptPropertyAttribute("6a510bdef2c904e42825cefa0190a6de")]
        [SerializeField] public UnityEngine.Object m_acceptUI = default;
        [SerializeField] public UnityEngine.Camera m_mainCamera = default;
        [SerializeField] public UnityEngine.Camera m_cutSceneCamera = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_TimerUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_SelectionUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_resultsUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_cinematicOverlayObj),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_leaderboardUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_hudButtonsUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_acceptUI),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_mainCamera),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_cutSceneCamera),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
