/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ActionLibrary")]
    [LuaRegisterType(0xb64a5ed95134aea2, typeof(LuaBehaviour))]
    public class ActionLibrary : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e570eb8e9cade074191ff114bceb994d";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("6bbfc1ed25f4b2e4b845f812887c8ece")]
        [SerializeField] public UnityEngine.Object m_Bark = default;
        [LuaScriptPropertyAttribute("6bbfc1ed25f4b2e4b845f812887c8ece")]
        [SerializeField] public UnityEngine.Object m_Bite = default;
        [LuaScriptPropertyAttribute("6bbfc1ed25f4b2e4b845f812887c8ece")]
        [SerializeField] public UnityEngine.Object m_Scratch = default;
        [LuaScriptPropertyAttribute("6bbfc1ed25f4b2e4b845f812887c8ece")]
        [SerializeField] public UnityEngine.Object m_Tackle = default;
        [LuaScriptPropertyAttribute("6bbfc1ed25f4b2e4b845f812887c8ece")]
        [SerializeField] public UnityEngine.Object m_LightningLash = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Bark),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Bite),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Scratch),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Tackle),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_LightningLash),
            };
        }
    }
}

#endif
