/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BattleGroundController")]
    [LuaRegisterType(0xa71c401df7e9a920, typeof(LuaBehaviour))]
    public class BattleGroundController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0d74f6f717fdb544fa38955a6b6462c7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_battleGround = default;
        [SerializeField] public UnityEngine.Transform m_playerPoint = default;
        [SerializeField] public UnityEngine.Transform m_enemyPoint = default;
        [SerializeField] public UnityEngine.GameObject m_playerCreature = default;
        [SerializeField] public UnityEngine.GameObject m_enemyCreature = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_battleGround),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_playerPoint),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_enemyPoint),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_playerCreature),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_enemyCreature),
            };
        }
    }
}

#endif
