/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BillboardScriptBattleCam")]
    [LuaRegisterType(0x8dc64d5513fcf114, typeof(LuaBehaviour))]
    public class BillboardScriptBattleCam : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f60c72160913eaf4a88ebdc3bff72519";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_locUp = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_locUp),
            };
        }
    }
}

#endif
