/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraManager")]
    [LuaRegisterType(0x932352b34a99f09d, typeof(LuaBehaviour))]
    public class CameraManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e989705792f21614b94d441df1d09eb3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_mainCamera = default;
        [SerializeField] public UnityEngine.GameObject m_battleCamera = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_mainCamera),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_battleCamera),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CameraManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
