/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DropLootTable")]
    [LuaRegisterType(0x2146356b36fd73a, typeof(LuaScriptableObject))]
    public class DropLootTable : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "23cd905668bc38c409bff901e234a5e8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<System.String> m_lootTableIDS = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> m_lootTableAmounts = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> m_lootTableWeights = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lootTableIDS),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_lootTableAmounts),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_lootTableWeights),
            };
        }
    }
}

#endif
