/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HatchEggUI")]
    [LuaRegisterType(0xd33d39133a0b4074, typeof(LuaBehaviour))]
    public class HatchEggUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d10bfad5931775046ae747fd04637451";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AnimationCurve m_fallInAnimationCurve = default;
        [SerializeField] public UnityEngine.AnimationCurve m_eggShakeAnimationCurve = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_cracks = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_fallInAnimationCurve),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_eggShakeAnimationCurve),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_cracks),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HatchEggUI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
