/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HatcherySlotController")]
    [LuaRegisterType(0x4fd879e1ef279b09, typeof(LuaBehaviour))]
    public class HatcherySlotController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3e9b3cd95221ea2488c5819a8afadc1f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_eggSlot = default;
        [SerializeField] public UnityEngine.GameObject m_meterUI = default;
        [SerializeField] public System.Double m_slotId = 1;
        [SerializeField] public UnityEngine.SpriteRenderer m_eggSprite = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_eggSlot),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_meterUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_slotId),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_eggSprite),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HatcherySlotController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
