/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/InteractableObject")]
    [LuaRegisterType(0x4b631b7218911e30, typeof(LuaBehaviour))]
    public class InteractableObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "024595455f0b6ee4f86a78bb213b1738";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_objectType = "";
        [SerializeField] public UnityEngine.Transform m_timerPoint = default;
        [SerializeField] public System.Double m_duration = 5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objectType),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_timerPoint),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_duration),
            };
        }
    }
}

#endif
