/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ItemLibrary")]
    [LuaRegisterType(0xa2ae165dddc78079, typeof(LuaBehaviour))]
    public class ItemLibrary : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "74392d207c384d448b861555e36cf24d";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("2f02479985df9dd46861ae8145efd00b")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_itemDatas = default;
        [LuaScriptPropertyAttribute("36cff7809ecd4cb4fadbd08fcdf6c9af")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_consumableDatas = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_itemDatas),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_consumableDatas),
            };
        }
    }
}

#endif
