/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/MaterialBase")]
    [LuaRegisterType(0x99d1daa1e76a24e5, typeof(LuaScriptableObject))]
    public class MaterialBase : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "2f02479985df9dd46861ae8145efd00b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_id = "";
        [SerializeField] public System.String m_displayName = "";
        [SerializeField] public UnityEngine.Texture m_sprite = default;
        [SerializeField] public System.String m_description = "";
        [SerializeField] public System.String m_element = "";
        [SerializeField] public System.Double m_rarity = 0;
        [SerializeField] public System.Double m_value = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_id),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_displayName),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_sprite),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_description),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_element),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_rarity),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_value),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MaterialBase/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
