/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/MonsterBase")]
    [LuaRegisterType(0x3606546863690abc, typeof(LuaScriptableObject))]
    public class MonsterBase : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "d2f77d2881e7f6941bb149becef8f82a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_MonsterName = "";
        [SerializeField] public System.String m_MonsterElement = "";
        [SerializeField] public System.Double m_MaxHP = 0;
        [SerializeField] public System.Double m_MaxMana = 0;
        [SerializeField] public System.Collections.Generic.List<System.String> m_MonsterActions = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_MonsterName),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_MonsterElement),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_MaxHP),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_MaxMana),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_MonsterActions),
            };
        }
    }
}

#endif
