/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MonsterLibrary")]
    [LuaRegisterType(0x6b8becbd0d9862dc, typeof(LuaBehaviour))]
    public class MonsterLibrary : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9abba2910f61fc14d84367cd1ebea173";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("d2f77d2881e7f6941bb149becef8f82a")]
        [SerializeField] public UnityEngine.Object m_Zapkit = default;
        [LuaScriptPropertyAttribute("d2f77d2881e7f6941bb149becef8f82a")]
        [SerializeField] public UnityEngine.Object m_Terakita = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Zapkit),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Terakita),
            };
        }
    }
}

#endif
