/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MonsterLibrary")]
    [LuaRegisterType(0x6b8becbd0d9862dc, typeof(LuaBehaviour))]
    public class MonsterLibrary : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9abba2910f61fc14d84367cd1ebea173";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("d2f77d2881e7f6941bb149becef8f82a")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_MonsterDatas = default;
        [SerializeField] public UnityEngine.Sprite m_airEggSprite = default;
        [SerializeField] public UnityEngine.Sprite m_earthEggSprite = default;
        [SerializeField] public UnityEngine.Sprite m_waterEggSprite = default;
        [SerializeField] public UnityEngine.Texture m_airEggTex = default;
        [SerializeField] public UnityEngine.Texture m_earthEggTex = default;
        [SerializeField] public UnityEngine.Texture m_waterEggTexe = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_MonsterDatas),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_airEggSprite),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_earthEggSprite),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_waterEggSprite),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_airEggTex),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_earthEggTex),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_waterEggTexe),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MonsterLibrary/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
