/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/OrthoCamera")]
    [LuaRegisterType(0x181049dca6c9232e, typeof(LuaBehaviour))]
    public class OrthoCamera : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ce68b7a482990224db7b29eceb4aaeba";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Camera _Camera = default;
        [SerializeField] public System.Double _MinX = -50;
        [SerializeField] public System.Double _MaxX = 50;
        [SerializeField] public System.Double _MinZ = -50;
        [SerializeField] public System.Double _MaxZ = 50;
        [SerializeField] public System.Double _MoveSpeed = 1;
        [SerializeField] public System.Double _ZoomSpeed = 1;
        [SerializeField] public System.Double _Zoom = 10;
        [SerializeField] public System.Double _ZoomMin = 5;
        [SerializeField] public System.Double _ZoomMax = 20;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _Camera),
                CreateSerializedProperty(_script.GetPropertyAt(1), _MinX),
                CreateSerializedProperty(_script.GetPropertyAt(2), _MaxX),
                CreateSerializedProperty(_script.GetPropertyAt(3), _MinZ),
                CreateSerializedProperty(_script.GetPropertyAt(4), _MaxZ),
                CreateSerializedProperty(_script.GetPropertyAt(5), _MoveSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(6), _ZoomSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(7), _Zoom),
                CreateSerializedProperty(_script.GetPropertyAt(8), _ZoomMin),
                CreateSerializedProperty(_script.GetPropertyAt(9), _ZoomMax),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/OrthoCamera/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
