/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "500c8e2431917754ca05bfd472cfeb43";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_elementsIcons = default;
        [SerializeField] public UnityEngine.GameObject m_BattleScreenOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_FourButtonOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_ResultsLabelObj = default;
        [SerializeField] public UnityEngine.GameObject m_TimerUIObject = default;
        [SerializeField] public UnityEngine.GameObject m_HatcherySelectionObj = default;
        [SerializeField] public UnityEngine.GameObject m_NameMonsterUIObj = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_elementsIcons),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_BattleScreenOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_FourButtonOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_ResultsLabelObj),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_TimerUIObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_HatcherySelectionObj),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_NameMonsterUIObj),
            };
        }
    }
}

#endif
