/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/WorldMonsterBehaviour")]
    [LuaRegisterType(0xc5204b9f172f41be, typeof(LuaBehaviour))]
    public class WorldMonsterBehaviour : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "88c3a44201a0b38489cf5b82411489a6";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_followDistance = 5;
        [SerializeField] public UnityEngine.Animator m_anim = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_followDistance),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_anim),
            };
        }
    }
}

#endif
