/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/WorldMonsterSpawner")]
    [LuaRegisterType(0x87816cfd7cf952b9, typeof(LuaBehaviour))]
    public class WorldMonsterSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1c23e29f7b4e566499d59a62530b1609";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_worldMonsterPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_worldMonsterPrefab),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/WorldMonsterSpawner/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
